#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ThucTap_ThietLapCauHinh")]
	public partial class ThietLapCauHinhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMB_PhanHe(MB_PhanHe instance);
    partial void UpdateMB_PhanHe(MB_PhanHe instance);
    partial void DeleteMB_PhanHe(MB_PhanHe instance);
    partial void InsertMB_Truong_PhanHe(MB_Truong_PhanHe instance);
    partial void UpdateMB_Truong_PhanHe(MB_Truong_PhanHe instance);
    partial void DeleteMB_Truong_PhanHe(MB_Truong_PhanHe instance);
    partial void InsertMB_Truong(MB_Truong instance);
    partial void UpdateMB_Truong(MB_Truong instance);
    partial void DeleteMB_Truong(MB_Truong instance);
    #endregion
		
		public ThietLapCauHinhDataContext() : 
				base(global::DAO.Properties.Settings.Default.ThucTap_ThietLapCauHinhConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThietLapCauHinhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThietLapCauHinhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThietLapCauHinhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThietLapCauHinhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MB_PhanHe> MB_PhanHes
		{
			get
			{
				return this.GetTable<MB_PhanHe>();
			}
		}
		
		public System.Data.Linq.Table<MB_Truong_PhanHe> MB_Truong_PhanHes
		{
			get
			{
				return this.GetTable<MB_Truong_PhanHe>();
			}
		}
		
		public System.Data.Linq.Table<MB_Truong> MB_Truongs
		{
			get
			{
				return this.GetTable<MB_Truong>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Sua_PhanHe")]
		public int sp_Sua_PhanHe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string ten_PhanHe, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> hienThi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, ten_PhanHe, ghiChu, hienThi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Them_PhanHe")]
		public int sp_Them_PhanHe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string maPhanHe, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string ten_PhanHe, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string ghiChu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, maPhanHe, ten_PhanHe, ghiChu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Xoa_PhanHe")]
		public int sp_Xoa_PhanHe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Show_PhanHe")]
		public ISingleResult<sp_Show_PhanHeResult> sp_Show_PhanHe()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Show_PhanHeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Show_Truong")]
		public ISingleResult<sp_Show_TruongResult> sp_Show_Truong()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Show_TruongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Sua_Truong")]
		public int sp_Sua_Truong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string maTruong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string ten_Truong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string truocThuocBo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string duongDanLogo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isHienThi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSuDungRieng", DbType="Bit")] System.Nullable<bool> isSuDungRieng, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string thongTinRieng, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Loai", DbType="Int")] System.Nullable<int> loai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, maTruong, ten_Truong, truocThuocBo, duongDanLogo, isHienThi, isSuDungRieng, thongTinRieng, ghiChu, loai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Them_Truong")]
		public int sp_Them_Truong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string maTruong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string ten_Truong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string truocThuocBo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string duongDanLogo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isHienThi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSuDungRieng", DbType="Bit")] System.Nullable<bool> isSuDungRieng, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string thongTinRieng, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Loai", DbType="Int")] System.Nullable<int> loai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, maTruong, ten_Truong, truocThuocBo, duongDanLogo, isHienThi, isSuDungRieng, thongTinRieng, ghiChu, loai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Xoa_Truong")]
		public int sp_Xoa_Truong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Show_Truong_PhanHe")]
		public ISingleResult<sp_Show_Truong_PhanHeResult> sp_Show_Truong_PhanHe()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Show_Truong_PhanHeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Sua_Truong_PhanHe")]
		public int sp_Sua_Truong_PhanHe(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDTruong", DbType="Int")] System.Nullable<int> iDTruong, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDPhanHe", DbType="Int")] System.Nullable<int> iDPhanHe, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url", DbType="NVarChar(500)")] string url, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url_2", DbType="NVarChar(500)")] string url_2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url_3", DbType="NVarChar(500)")] string url_3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrlSocket", DbType="NVarChar(500)")] string urlSocket, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubAPI", DbType="NVarChar(200)")] string subAPI, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubAPI_2", DbType="NVarChar(200)")] string subAPI_2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubAPI_3", DbType="NVarChar(200)")] string subAPI_3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(500)")] string ghiChu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Warning_RequireSurvey", DbType="NVarChar(1000)")] string warning_RequireSurvey, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeaturesRequireSurvey", DbType="NVarChar(250)")] string featuresRequireSurvey, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionEgovAPI", DbType="Int")] System.Nullable<int> versionEgovAPI, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrlPayment", DbType="NVarChar(500)")] string urlPayment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionStudentAPI", DbType="Int")] System.Nullable<int> versionStudentAPI, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WarningMessage", DbType="NVarChar(1000)")] string warningMessage, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasAds", DbType="Bit")] System.Nullable<bool> hasAds, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WebsiteUrl", DbType="NVarChar(500)")] string websiteUrl, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionWeb", DbType="Int")] System.Nullable<int> versionWeb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseHTMLSalaryView", DbType="Bit")] System.Nullable<bool> useHTMLSalaryView)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, iDTruong, iDPhanHe, url, url_2, url_3, urlSocket, subAPI, subAPI_2, subAPI_3, ghiChu, warning_RequireSurvey, featuresRequireSurvey, versionEgovAPI, urlPayment, versionStudentAPI, warningMessage, hasAds, websiteUrl, versionWeb, useHTMLSalaryView);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Them_Truong_PhanHe")]
		public int sp_Them_Truong_PhanHe(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDTruong", DbType="Int")] System.Nullable<int> iDTruong, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDPhanHe", DbType="Int")] System.Nullable<int> iDPhanHe, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url", DbType="NVarChar(500)")] string url, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url_2", DbType="NVarChar(500)")] string url_2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url_3", DbType="NVarChar(500)")] string url_3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrlSocket", DbType="NVarChar(500)")] string urlSocket, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubAPI", DbType="NVarChar(200)")] string subAPI, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubAPI_2", DbType="NVarChar(200)")] string subAPI_2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubAPI_3", DbType="NVarChar(200)")] string subAPI_3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(500)")] string ghiChu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Warning_RequireSurvey", DbType="NVarChar(1000)")] string warning_RequireSurvey, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeaturesRequireSurvey", DbType="NVarChar(250)")] string featuresRequireSurvey, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionEgovAPI", DbType="Int")] System.Nullable<int> versionEgovAPI, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrlPayment", DbType="NVarChar(500)")] string urlPayment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionStudentAPI", DbType="Int")] System.Nullable<int> versionStudentAPI, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WarningMessage", DbType="NVarChar(1000)")] string warningMessage, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasAds", DbType="Bit")] System.Nullable<bool> hasAds, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WebsiteUrl", DbType="NVarChar(500)")] string websiteUrl, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VersionWeb", DbType="Int")] System.Nullable<int> versionWeb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseHTMLSalaryView", DbType="Bit")] System.Nullable<bool> useHTMLSalaryView)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDTruong, iDPhanHe, url, url_2, url_3, urlSocket, subAPI, subAPI_2, subAPI_3, ghiChu, warning_RequireSurvey, featuresRequireSurvey, versionEgovAPI, urlPayment, versionStudentAPI, warningMessage, hasAds, websiteUrl, versionWeb, useHTMLSalaryView);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Xoa_Truong_PhanHe")]
		public int sp_Xoa_Truong_PhanHe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MB_PhanHe")]
	public partial class MB_PhanHe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaPhanHe;
		
		private string _TenPhanHe;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _IsHienThi;
		
		private System.Nullable<int> _NguoiTao;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<int> _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaPhanHeChanging(string value);
    partial void OnMaPhanHeChanged();
    partial void OnTenPhanHeChanging(string value);
    partial void OnTenPhanHeChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnIsHienThiChanging(System.Nullable<bool> value);
    partial void OnIsHienThiChanged();
    partial void OnNguoiTaoChanging(System.Nullable<int> value);
    partial void OnNguoiTaoChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiCapNhatChanging(System.Nullable<int> value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public MB_PhanHe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanHe", DbType="NVarChar(20)")]
		public string MaPhanHe
		{
			get
			{
				return this._MaPhanHe;
			}
			set
			{
				if ((this._MaPhanHe != value))
				{
					this.OnMaPhanHeChanging(value);
					this.SendPropertyChanging();
					this._MaPhanHe = value;
					this.SendPropertyChanged("MaPhanHe");
					this.OnMaPhanHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhanHe", DbType="NVarChar(200)")]
		public string TenPhanHe
		{
			get
			{
				return this._TenPhanHe;
			}
			set
			{
				if ((this._TenPhanHe != value))
				{
					this.OnTenPhanHeChanging(value);
					this.SendPropertyChanging();
					this._TenPhanHe = value;
					this.SendPropertyChanged("TenPhanHe");
					this.OnTenPhanHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHienThi", DbType="Bit")]
		public System.Nullable<bool> IsHienThi
		{
			get
			{
				return this._IsHienThi;
			}
			set
			{
				if ((this._IsHienThi != value))
				{
					this.OnIsHienThiChanging(value);
					this.SendPropertyChanging();
					this._IsHienThi = value;
					this.SendPropertyChanged("IsHienThi");
					this.OnIsHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="Int")]
		public System.Nullable<int> NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="Int")]
		public System.Nullable<int> NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MB_Truong_PhanHe")]
	public partial class MB_Truong_PhanHe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IDTruong;
		
		private System.Nullable<int> _IDPhanHe;
		
		private string _Url;
		
		private string _Url_2;
		
		private string _Url_3;
		
		private string _UrlSocket;
		
		private string _SubAPI;
		
		private string _SubAPI_2;
		
		private string _SubAPI_3;
		
		private string _GhiChu;
		
		private string _Warning_RequireSurvey;
		
		private string _FeaturesRequireSurvey;
		
		private System.Nullable<int> _NguoiTao;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<int> _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private System.Nullable<int> _VersionEgovAPI;
		
		private string _UrlPayment;
		
		private System.Nullable<int> _VersionStudentAPI;
		
		private string _WarningMessage;
		
		private System.Nullable<bool> _HasAds;
		
		private string _WebsiteUrl;
		
		private System.Nullable<int> _VersionWeb;
		
		private System.Nullable<bool> _UseHTMLSalaryView;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIDTruongChanging(System.Nullable<int> value);
    partial void OnIDTruongChanged();
    partial void OnIDPhanHeChanging(System.Nullable<int> value);
    partial void OnIDPhanHeChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnUrl_2Changing(string value);
    partial void OnUrl_2Changed();
    partial void OnUrl_3Changing(string value);
    partial void OnUrl_3Changed();
    partial void OnUrlSocketChanging(string value);
    partial void OnUrlSocketChanged();
    partial void OnSubAPIChanging(string value);
    partial void OnSubAPIChanged();
    partial void OnSubAPI_2Changing(string value);
    partial void OnSubAPI_2Changed();
    partial void OnSubAPI_3Changing(string value);
    partial void OnSubAPI_3Changed();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnWarning_RequireSurveyChanging(string value);
    partial void OnWarning_RequireSurveyChanged();
    partial void OnFeaturesRequireSurveyChanging(string value);
    partial void OnFeaturesRequireSurveyChanged();
    partial void OnNguoiTaoChanging(System.Nullable<int> value);
    partial void OnNguoiTaoChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiCapNhatChanging(System.Nullable<int> value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnVersionEgovAPIChanging(System.Nullable<int> value);
    partial void OnVersionEgovAPIChanged();
    partial void OnUrlPaymentChanging(string value);
    partial void OnUrlPaymentChanged();
    partial void OnVersionStudentAPIChanging(System.Nullable<int> value);
    partial void OnVersionStudentAPIChanged();
    partial void OnWarningMessageChanging(string value);
    partial void OnWarningMessageChanged();
    partial void OnHasAdsChanging(System.Nullable<bool> value);
    partial void OnHasAdsChanged();
    partial void OnWebsiteUrlChanging(string value);
    partial void OnWebsiteUrlChanged();
    partial void OnVersionWebChanging(System.Nullable<int> value);
    partial void OnVersionWebChanged();
    partial void OnUseHTMLSalaryViewChanging(System.Nullable<bool> value);
    partial void OnUseHTMLSalaryViewChanged();
    #endregion
		
		public MB_Truong_PhanHe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTruong", DbType="Int")]
		public System.Nullable<int> IDTruong
		{
			get
			{
				return this._IDTruong;
			}
			set
			{
				if ((this._IDTruong != value))
				{
					this.OnIDTruongChanging(value);
					this.SendPropertyChanging();
					this._IDTruong = value;
					this.SendPropertyChanged("IDTruong");
					this.OnIDTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhanHe", DbType="Int")]
		public System.Nullable<int> IDPhanHe
		{
			get
			{
				return this._IDPhanHe;
			}
			set
			{
				if ((this._IDPhanHe != value))
				{
					this.OnIDPhanHeChanging(value);
					this.SendPropertyChanging();
					this._IDPhanHe = value;
					this.SendPropertyChanged("IDPhanHe");
					this.OnIDPhanHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(500)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url_2", DbType="NVarChar(500)")]
		public string Url_2
		{
			get
			{
				return this._Url_2;
			}
			set
			{
				if ((this._Url_2 != value))
				{
					this.OnUrl_2Changing(value);
					this.SendPropertyChanging();
					this._Url_2 = value;
					this.SendPropertyChanged("Url_2");
					this.OnUrl_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url_3", DbType="NVarChar(500)")]
		public string Url_3
		{
			get
			{
				return this._Url_3;
			}
			set
			{
				if ((this._Url_3 != value))
				{
					this.OnUrl_3Changing(value);
					this.SendPropertyChanging();
					this._Url_3 = value;
					this.SendPropertyChanged("Url_3");
					this.OnUrl_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlSocket", DbType="NVarChar(500)")]
		public string UrlSocket
		{
			get
			{
				return this._UrlSocket;
			}
			set
			{
				if ((this._UrlSocket != value))
				{
					this.OnUrlSocketChanging(value);
					this.SendPropertyChanging();
					this._UrlSocket = value;
					this.SendPropertyChanged("UrlSocket");
					this.OnUrlSocketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubAPI", DbType="NVarChar(200)")]
		public string SubAPI
		{
			get
			{
				return this._SubAPI;
			}
			set
			{
				if ((this._SubAPI != value))
				{
					this.OnSubAPIChanging(value);
					this.SendPropertyChanging();
					this._SubAPI = value;
					this.SendPropertyChanged("SubAPI");
					this.OnSubAPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubAPI_2", DbType="NVarChar(200)")]
		public string SubAPI_2
		{
			get
			{
				return this._SubAPI_2;
			}
			set
			{
				if ((this._SubAPI_2 != value))
				{
					this.OnSubAPI_2Changing(value);
					this.SendPropertyChanging();
					this._SubAPI_2 = value;
					this.SendPropertyChanged("SubAPI_2");
					this.OnSubAPI_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubAPI_3", DbType="NVarChar(200)")]
		public string SubAPI_3
		{
			get
			{
				return this._SubAPI_3;
			}
			set
			{
				if ((this._SubAPI_3 != value))
				{
					this.OnSubAPI_3Changing(value);
					this.SendPropertyChanging();
					this._SubAPI_3 = value;
					this.SendPropertyChanged("SubAPI_3");
					this.OnSubAPI_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Warning_RequireSurvey", DbType="NVarChar(1000)")]
		public string Warning_RequireSurvey
		{
			get
			{
				return this._Warning_RequireSurvey;
			}
			set
			{
				if ((this._Warning_RequireSurvey != value))
				{
					this.OnWarning_RequireSurveyChanging(value);
					this.SendPropertyChanging();
					this._Warning_RequireSurvey = value;
					this.SendPropertyChanged("Warning_RequireSurvey");
					this.OnWarning_RequireSurveyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeaturesRequireSurvey", DbType="NVarChar(250)")]
		public string FeaturesRequireSurvey
		{
			get
			{
				return this._FeaturesRequireSurvey;
			}
			set
			{
				if ((this._FeaturesRequireSurvey != value))
				{
					this.OnFeaturesRequireSurveyChanging(value);
					this.SendPropertyChanging();
					this._FeaturesRequireSurvey = value;
					this.SendPropertyChanged("FeaturesRequireSurvey");
					this.OnFeaturesRequireSurveyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="Int")]
		public System.Nullable<int> NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="Int")]
		public System.Nullable<int> NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionEgovAPI", DbType="Int")]
		public System.Nullable<int> VersionEgovAPI
		{
			get
			{
				return this._VersionEgovAPI;
			}
			set
			{
				if ((this._VersionEgovAPI != value))
				{
					this.OnVersionEgovAPIChanging(value);
					this.SendPropertyChanging();
					this._VersionEgovAPI = value;
					this.SendPropertyChanged("VersionEgovAPI");
					this.OnVersionEgovAPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlPayment", DbType="NVarChar(500)")]
		public string UrlPayment
		{
			get
			{
				return this._UrlPayment;
			}
			set
			{
				if ((this._UrlPayment != value))
				{
					this.OnUrlPaymentChanging(value);
					this.SendPropertyChanging();
					this._UrlPayment = value;
					this.SendPropertyChanged("UrlPayment");
					this.OnUrlPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionStudentAPI", DbType="Int")]
		public System.Nullable<int> VersionStudentAPI
		{
			get
			{
				return this._VersionStudentAPI;
			}
			set
			{
				if ((this._VersionStudentAPI != value))
				{
					this.OnVersionStudentAPIChanging(value);
					this.SendPropertyChanging();
					this._VersionStudentAPI = value;
					this.SendPropertyChanged("VersionStudentAPI");
					this.OnVersionStudentAPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarningMessage", DbType="NVarChar(1000)")]
		public string WarningMessage
		{
			get
			{
				return this._WarningMessage;
			}
			set
			{
				if ((this._WarningMessage != value))
				{
					this.OnWarningMessageChanging(value);
					this.SendPropertyChanging();
					this._WarningMessage = value;
					this.SendPropertyChanged("WarningMessage");
					this.OnWarningMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasAds", DbType="Bit")]
		public System.Nullable<bool> HasAds
		{
			get
			{
				return this._HasAds;
			}
			set
			{
				if ((this._HasAds != value))
				{
					this.OnHasAdsChanging(value);
					this.SendPropertyChanging();
					this._HasAds = value;
					this.SendPropertyChanged("HasAds");
					this.OnHasAdsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebsiteUrl", DbType="NVarChar(500)")]
		public string WebsiteUrl
		{
			get
			{
				return this._WebsiteUrl;
			}
			set
			{
				if ((this._WebsiteUrl != value))
				{
					this.OnWebsiteUrlChanging(value);
					this.SendPropertyChanging();
					this._WebsiteUrl = value;
					this.SendPropertyChanged("WebsiteUrl");
					this.OnWebsiteUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionWeb", DbType="Int")]
		public System.Nullable<int> VersionWeb
		{
			get
			{
				return this._VersionWeb;
			}
			set
			{
				if ((this._VersionWeb != value))
				{
					this.OnVersionWebChanging(value);
					this.SendPropertyChanging();
					this._VersionWeb = value;
					this.SendPropertyChanged("VersionWeb");
					this.OnVersionWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseHTMLSalaryView", DbType="Bit")]
		public System.Nullable<bool> UseHTMLSalaryView
		{
			get
			{
				return this._UseHTMLSalaryView;
			}
			set
			{
				if ((this._UseHTMLSalaryView != value))
				{
					this.OnUseHTMLSalaryViewChanging(value);
					this.SendPropertyChanging();
					this._UseHTMLSalaryView = value;
					this.SendPropertyChanged("UseHTMLSalaryView");
					this.OnUseHTMLSalaryViewChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MB_Truong")]
	public partial class MB_Truong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaTruong;
		
		private string _TenTruong;
		
		private string _TruocThuocBo;
		
		private string _DuongDanLogo;
		
		private bool _IsHienThi;
		
		private bool _IsSuDungRieng;
		
		private string _ThongTinRieng;
		
		private string _GhiChu;
		
		private System.Nullable<int> _Loai;
		
		private System.Nullable<int> _NguoiTao;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<int> _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaTruongChanging(string value);
    partial void OnMaTruongChanged();
    partial void OnTenTruongChanging(string value);
    partial void OnTenTruongChanged();
    partial void OnTruocThuocBoChanging(string value);
    partial void OnTruocThuocBoChanged();
    partial void OnDuongDanLogoChanging(string value);
    partial void OnDuongDanLogoChanged();
    partial void OnIsHienThiChanging(bool value);
    partial void OnIsHienThiChanged();
    partial void OnIsSuDungRiengChanging(bool value);
    partial void OnIsSuDungRiengChanged();
    partial void OnThongTinRiengChanging(string value);
    partial void OnThongTinRiengChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnLoaiChanging(System.Nullable<int> value);
    partial void OnLoaiChanged();
    partial void OnNguoiTaoChanging(System.Nullable<int> value);
    partial void OnNguoiTaoChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiCapNhatChanging(System.Nullable<int> value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public MB_Truong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruong", DbType="NVarChar(20)")]
		public string MaTruong
		{
			get
			{
				return this._MaTruong;
			}
			set
			{
				if ((this._MaTruong != value))
				{
					this.OnMaTruongChanging(value);
					this.SendPropertyChanging();
					this._MaTruong = value;
					this.SendPropertyChanged("MaTruong");
					this.OnMaTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTruong", DbType="NVarChar(200)")]
		public string TenTruong
		{
			get
			{
				return this._TenTruong;
			}
			set
			{
				if ((this._TenTruong != value))
				{
					this.OnTenTruongChanging(value);
					this.SendPropertyChanging();
					this._TenTruong = value;
					this.SendPropertyChanged("TenTruong");
					this.OnTenTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruocThuocBo", DbType="NVarChar(200)")]
		public string TruocThuocBo
		{
			get
			{
				return this._TruocThuocBo;
			}
			set
			{
				if ((this._TruocThuocBo != value))
				{
					this.OnTruocThuocBoChanging(value);
					this.SendPropertyChanging();
					this._TruocThuocBo = value;
					this.SendPropertyChanged("TruocThuocBo");
					this.OnTruocThuocBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuongDanLogo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DuongDanLogo
		{
			get
			{
				return this._DuongDanLogo;
			}
			set
			{
				if ((this._DuongDanLogo != value))
				{
					this.OnDuongDanLogoChanging(value);
					this.SendPropertyChanging();
					this._DuongDanLogo = value;
					this.SendPropertyChanged("DuongDanLogo");
					this.OnDuongDanLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHienThi", DbType="Bit NOT NULL")]
		public bool IsHienThi
		{
			get
			{
				return this._IsHienThi;
			}
			set
			{
				if ((this._IsHienThi != value))
				{
					this.OnIsHienThiChanging(value);
					this.SendPropertyChanging();
					this._IsHienThi = value;
					this.SendPropertyChanged("IsHienThi");
					this.OnIsHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSuDungRieng", DbType="Bit NOT NULL")]
		public bool IsSuDungRieng
		{
			get
			{
				return this._IsSuDungRieng;
			}
			set
			{
				if ((this._IsSuDungRieng != value))
				{
					this.OnIsSuDungRiengChanging(value);
					this.SendPropertyChanging();
					this._IsSuDungRieng = value;
					this.SendPropertyChanged("IsSuDungRieng");
					this.OnIsSuDungRiengChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinRieng", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ThongTinRieng
		{
			get
			{
				return this._ThongTinRieng;
			}
			set
			{
				if ((this._ThongTinRieng != value))
				{
					this.OnThongTinRiengChanging(value);
					this.SendPropertyChanging();
					this._ThongTinRieng = value;
					this.SendPropertyChanged("ThongTinRieng");
					this.OnThongTinRiengChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="Int")]
		public System.Nullable<int> Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="Int")]
		public System.Nullable<int> NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="Int")]
		public System.Nullable<int> NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_Show_PhanHeResult
	{
		
		private int _Id;
		
		private string _MaPhanHe;
		
		private string _TenPhanHe;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _IsHienThi;
		
		private System.Nullable<int> _NguoiTao;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<int> _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		public sp_Show_PhanHeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanHe", DbType="NVarChar(20)")]
		public string MaPhanHe
		{
			get
			{
				return this._MaPhanHe;
			}
			set
			{
				if ((this._MaPhanHe != value))
				{
					this._MaPhanHe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhanHe", DbType="NVarChar(200)")]
		public string TenPhanHe
		{
			get
			{
				return this._TenPhanHe;
			}
			set
			{
				if ((this._TenPhanHe != value))
				{
					this._TenPhanHe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHienThi", DbType="Bit")]
		public System.Nullable<bool> IsHienThi
		{
			get
			{
				return this._IsHienThi;
			}
			set
			{
				if ((this._IsHienThi != value))
				{
					this._IsHienThi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="Int")]
		public System.Nullable<int> NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this._NguoiTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this._NgayTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="Int")]
		public System.Nullable<int> NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this._NguoiCapNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this._NgayCapNhat = value;
				}
			}
		}
	}
	
	public partial class sp_Show_TruongResult
	{
		
		private int _Id;
		
		private string _MaTruong;
		
		private string _TenTruong;
		
		private string _TruocThuocBo;
		
		private string _DuongDanLogo;
		
		private bool _IsHienThi;
		
		private bool _IsSuDungRieng;
		
		private string _ThongTinRieng;
		
		private string _GhiChu;
		
		private System.Nullable<int> _Loai;
		
		private System.Nullable<int> _NguoiTao;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<int> _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		public sp_Show_TruongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruong", DbType="NVarChar(20)")]
		public string MaTruong
		{
			get
			{
				return this._MaTruong;
			}
			set
			{
				if ((this._MaTruong != value))
				{
					this._MaTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTruong", DbType="NVarChar(200)")]
		public string TenTruong
		{
			get
			{
				return this._TenTruong;
			}
			set
			{
				if ((this._TenTruong != value))
				{
					this._TenTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruocThuocBo", DbType="NVarChar(200)")]
		public string TruocThuocBo
		{
			get
			{
				return this._TruocThuocBo;
			}
			set
			{
				if ((this._TruocThuocBo != value))
				{
					this._TruocThuocBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuongDanLogo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DuongDanLogo
		{
			get
			{
				return this._DuongDanLogo;
			}
			set
			{
				if ((this._DuongDanLogo != value))
				{
					this._DuongDanLogo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHienThi", DbType="Bit NOT NULL")]
		public bool IsHienThi
		{
			get
			{
				return this._IsHienThi;
			}
			set
			{
				if ((this._IsHienThi != value))
				{
					this._IsHienThi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSuDungRieng", DbType="Bit NOT NULL")]
		public bool IsSuDungRieng
		{
			get
			{
				return this._IsSuDungRieng;
			}
			set
			{
				if ((this._IsSuDungRieng != value))
				{
					this._IsSuDungRieng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinRieng", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ThongTinRieng
		{
			get
			{
				return this._ThongTinRieng;
			}
			set
			{
				if ((this._ThongTinRieng != value))
				{
					this._ThongTinRieng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="Int")]
		public System.Nullable<int> Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this._Loai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="Int")]
		public System.Nullable<int> NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this._NguoiTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this._NgayTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="Int")]
		public System.Nullable<int> NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this._NguoiCapNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this._NgayCapNhat = value;
				}
			}
		}
	}
	
	public partial class sp_Show_Truong_PhanHeResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _IDTruong;
		
		private System.Nullable<int> _IDPhanHe;
		
		private string _Url;
		
		private string _Url_2;
		
		private string _Url_3;
		
		private string _UrlSocket;
		
		private string _SubAPI;
		
		private string _SubAPI_2;
		
		private string _SubAPI_3;
		
		private string _GhiChu;
		
		private string _Warning_RequireSurvey;
		
		private string _FeaturesRequireSurvey;
		
		private System.Nullable<int> _NguoiTao;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<int> _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private System.Nullable<int> _VersionEgovAPI;
		
		private string _UrlPayment;
		
		private System.Nullable<int> _VersionStudentAPI;
		
		private string _WarningMessage;
		
		private System.Nullable<bool> _HasAds;
		
		private string _WebsiteUrl;
		
		private System.Nullable<int> _VersionWeb;
		
		private System.Nullable<bool> _UseHTMLSalaryView;
		
		public sp_Show_Truong_PhanHeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTruong", DbType="Int")]
		public System.Nullable<int> IDTruong
		{
			get
			{
				return this._IDTruong;
			}
			set
			{
				if ((this._IDTruong != value))
				{
					this._IDTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhanHe", DbType="Int")]
		public System.Nullable<int> IDPhanHe
		{
			get
			{
				return this._IDPhanHe;
			}
			set
			{
				if ((this._IDPhanHe != value))
				{
					this._IDPhanHe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(500)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url_2", DbType="NVarChar(500)")]
		public string Url_2
		{
			get
			{
				return this._Url_2;
			}
			set
			{
				if ((this._Url_2 != value))
				{
					this._Url_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url_3", DbType="NVarChar(500)")]
		public string Url_3
		{
			get
			{
				return this._Url_3;
			}
			set
			{
				if ((this._Url_3 != value))
				{
					this._Url_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlSocket", DbType="NVarChar(500)")]
		public string UrlSocket
		{
			get
			{
				return this._UrlSocket;
			}
			set
			{
				if ((this._UrlSocket != value))
				{
					this._UrlSocket = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubAPI", DbType="NVarChar(200)")]
		public string SubAPI
		{
			get
			{
				return this._SubAPI;
			}
			set
			{
				if ((this._SubAPI != value))
				{
					this._SubAPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubAPI_2", DbType="NVarChar(200)")]
		public string SubAPI_2
		{
			get
			{
				return this._SubAPI_2;
			}
			set
			{
				if ((this._SubAPI_2 != value))
				{
					this._SubAPI_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubAPI_3", DbType="NVarChar(200)")]
		public string SubAPI_3
		{
			get
			{
				return this._SubAPI_3;
			}
			set
			{
				if ((this._SubAPI_3 != value))
				{
					this._SubAPI_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Warning_RequireSurvey", DbType="NVarChar(1000)")]
		public string Warning_RequireSurvey
		{
			get
			{
				return this._Warning_RequireSurvey;
			}
			set
			{
				if ((this._Warning_RequireSurvey != value))
				{
					this._Warning_RequireSurvey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeaturesRequireSurvey", DbType="NVarChar(250)")]
		public string FeaturesRequireSurvey
		{
			get
			{
				return this._FeaturesRequireSurvey;
			}
			set
			{
				if ((this._FeaturesRequireSurvey != value))
				{
					this._FeaturesRequireSurvey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="Int")]
		public System.Nullable<int> NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this._NguoiTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this._NgayTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="Int")]
		public System.Nullable<int> NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this._NguoiCapNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this._NgayCapNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionEgovAPI", DbType="Int")]
		public System.Nullable<int> VersionEgovAPI
		{
			get
			{
				return this._VersionEgovAPI;
			}
			set
			{
				if ((this._VersionEgovAPI != value))
				{
					this._VersionEgovAPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlPayment", DbType="NVarChar(500)")]
		public string UrlPayment
		{
			get
			{
				return this._UrlPayment;
			}
			set
			{
				if ((this._UrlPayment != value))
				{
					this._UrlPayment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionStudentAPI", DbType="Int")]
		public System.Nullable<int> VersionStudentAPI
		{
			get
			{
				return this._VersionStudentAPI;
			}
			set
			{
				if ((this._VersionStudentAPI != value))
				{
					this._VersionStudentAPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarningMessage", DbType="NVarChar(1000)")]
		public string WarningMessage
		{
			get
			{
				return this._WarningMessage;
			}
			set
			{
				if ((this._WarningMessage != value))
				{
					this._WarningMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasAds", DbType="Bit")]
		public System.Nullable<bool> HasAds
		{
			get
			{
				return this._HasAds;
			}
			set
			{
				if ((this._HasAds != value))
				{
					this._HasAds = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebsiteUrl", DbType="NVarChar(500)")]
		public string WebsiteUrl
		{
			get
			{
				return this._WebsiteUrl;
			}
			set
			{
				if ((this._WebsiteUrl != value))
				{
					this._WebsiteUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionWeb", DbType="Int")]
		public System.Nullable<int> VersionWeb
		{
			get
			{
				return this._VersionWeb;
			}
			set
			{
				if ((this._VersionWeb != value))
				{
					this._VersionWeb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseHTMLSalaryView", DbType="Bit")]
		public System.Nullable<bool> UseHTMLSalaryView
		{
			get
			{
				return this._UseHTMLSalaryView;
			}
			set
			{
				if ((this._UseHTMLSalaryView != value))
				{
					this._UseHTMLSalaryView = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
